// Valid Roles
const env = process.env
export const ROLE = {
    CBC_ADMIN: env.CBC_ADMIN || 'CBC_ADMIN',
    CBC_MEMBER: env.CBC_MEMBER || 'CBC_MEMBER',
    CONTENT_CREATOR: env.CONTENT_CREATOR || 'CONTENT_CREATOR',
    CONTENT_PUBLISHER: env.CONTENT_PUBLISHER || 'CONTENT_PUBLISHER',
    CONTENT_REVIEWER: env.CONTENT_REVIEWER || 'CONTENT_REVIEWER',
    EDITOR: env.EDITOR || 'EDITOR',
    FRAC_ACCESS_COMPENTENCY: env.FRAC_COMPETENCY_MEMBER || 'FRAC_COMPETENCY_MEMBER',
    FRAC_ADMIN: env.FRAC_ADMIN || 'FRAC_ADMIN',
    FRAC_COMPETENCY_REVIEWER: env.FRAC_COMPETENCY_REVIEWER || 'FRAC_COMPETENCY_REVIEWER',
    FRAC_REVIEWER_ONE: env.FRAC_REVIEWER_L1 || 'FRAC_REVIEWER_L1',
    FRAC_REVIEWER_TWO: env.FRAC_REVIEWER_L2 || 'FRAC_REVIEWER_L2',
    IFU_MEMBER: env.IFU_MEMBER || 'IFU_MEMBER',
    MDO_ADMIN: env.MDO_ADMIN || 'MDO_ADMIN',
    PUBLIC: env.PUBLIC || 'PUBLIC',
    SPV_ADMIN: env.SPV_ADMIN || 'SPV_ADMIN',
    WAT_MEMBER: env.WAT_MEMBER || 'WAT_MEMBER',
}
